# Generated by Django 4.2.11 on 2024-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadAdvisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='neighborhood',
            field=models.CharField(max_length=100),
        ),
    ]
