# Generated by Django 4.2.11 on 2024-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadAdvisor', '0002_city_image_alter_review_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='neighborhood',
            field=models.CharField(default='', max_length=100),
        ),
    ]
