# Generated by Django 4.2.11 on 2024-04-08 00:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadAdvisor', '0003_city_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default={}), size=None),
        ),
    ]
