# Generated by Django 4.2.11 on 2024-04-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadAdvisor', '0004_alter_city_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='gallery',
        ),
        migrations.AddField(
            model_name='city',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
