# Generated by Django 4.2.11 on 2024-04-09 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadAdvisor', '0005_remove_city_gallery_city_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='neighborhood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=200), size=None),
        ),
    ]
