# Generated by Django 4.2.11 on 2024-04-09 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadAdvisor', '0007_alter_review_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='neighborhood',
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=9),
        ),
    ]
