# Generated by Django 4.2.11 on 2024-04-09 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadAdvisor', '0008_remove_city_neighborhood_alter_review_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
    ]
